#ddev-generated
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# Derived from the browsersync addition.
# This is to expose the vite dev port.
version: '3.6'
services:
  web:
    expose:
      - '3000'
    environment:
      # Set the vite-enabled js project here:
      - VITE_PROJECT_DIR=./
      # Expose the vite dev server's port (default 3000) here.
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3000:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3001:3000
